const router = require('express').Router();
const controller = require('./favorite.controller');
const authMiddleware = require('../../../middlewares/auth');
router.use('/add', authMiddleware);
router.use('/remove', authMiddleware);
router.use('/all', authMiddleware);
router.post('/add', controller.addFavorite);
router.post('/remove', controller.removeFavorite);
router.get('/all', controller.getEveryFavorite);
module.exports = router;
